### ISSUE TITLE
 Crash report reason unknown

### ISSUE THREAD

**Issue by EternalOne11** [AustereTony-MCMods/Enchantments-Control#1]
https://paste.dimdev.org/nujogeheha.mccrash
Got it when I tried to start up the game

**Comment by mattrix444** [comment]
confirmed, getting the same crash.

**Comment by AustereTony-MCMods** [comment]
_Good start as always..._

Hello, thank you for report. My bad. Didn't tested it on huge modpacks yet. Uploaded patched version (1.0.1) just now, so please check it out. NPE crash was caused by unreliable enchantment wrap process and it was rewritten.

**Comment by EternalOne11** [comment]
fixed for me in the new version
