### ISSUE TITLE
Server Crash with Silent Gems

### ISSUE THREAD

**Issue by Fireztonez** [AustereTony-MCMods/Enchantments-Control#14]
Hello, 
I work currently on a modpack where I used Silent Gems and I have to used Enchantments control to changes somes enchantments compatibility and somes other options, but right now, this is totally impossible to use Enchantment Control with Silent Gems on server. Everithing work's fine in signle player, but, the server crash when loading the modpack...

The crash look to be caused by the Silent Gems Enchantment Token.

Crash log: https://gist.github.com/Fireztonez/3e0328701d169b934e6f684ffbf70e0d

**Version :**
**Enchantments Control:** 1.1.4-0
**Forge:** 14.23.5.2838
**Silent's Gems:** 2.8.21+325
**Silent Lib:** 3.0.13+167

Thank's for your mod, really usefull, continue your great work!
Fireztonez

**Comment by AustereTony-MCMods** [comment]
Fixed in 1.1.5. If issue persists, please reopen this ticket.
