### ISSUE TITLE
Compatibility With Tinker's Construct

### ISSUE THREAD

**Issue by xlea99** [AustereTony-MCMods/Enchantments-Control#17]
Hello! This is an awesome mod and has helped a bunch with my modpack, but is there any chance you could make this compatible with Tinker's Construct tools? Idk how hard that would be, or if its even possible, but it would be SO cool to have enchantable TiC tools in my custom pack. 

Either way thanks for your time!!

**Comment by AustereTony-MCMods** [comment]
Hi.
TC has its own mechanic for tools and this tools can't be enchanted. I can't help, sorry.
