### ISSUE TITLE
[1.1.0]mention needed config reset in changelog

### ISSUE THREAD

**Issue by WarlordWossman** [AustereTony-MCMods/Enchantments-Control#2]
Just updated from 1.0.1 to 1.1.0 and getting this crash when trying to launch the game:
https://hastebin.com/emizacehen.php

**Comment by WarlordWossman** [comment]
Oh, I just saw the mentioned config reset by chance.
Can you put that into the version changelog next time? Got lot of mods to update and usually the changelog mentioning those needed resets works the best.

**Comment by AustereTony-MCMods** [comment]
Sure. Next time i will note it in changelog file and forge update checker changelog. Thank you for suggestion.
