### ISSUE TITLE
mod removes all contents of dungeon chests

### ISSUE THREAD

**Issue by sterh1275** [AustereTony-MCMods/Enchantments-Control#3]
Bug description:
1) I install the mod on 1.12.2 Forge 14.23.5.2775
  (no other mods installed for the purity of the test)
2) I do not change any settings in the configuration files
3) Create a world with a seed I know
4) The chests in which there was any Enchantments book are empty
(no books, no other loot)
5) Delete the mod, re-create the world - everything is in order

The problem occurs with any version of the mod

**Comment by AustereTony-MCMods** [comment]
Hello.
It was a major problem - mistake in asm transformer while patching EnchantRandomly#apply() method. I suppose it caused a lot of problems with enchanted content while world gen. Fixed in patch 1.1.1b. Please, report after testing.

**Comment by sterh1275** [comment]
Tested 1.1.2
Works great
Disabling Enchantment works perfectly in numerous tests.
Thank you for not giving up and supporting this very important mod.

**Comment by AustereTony-MCMods** [comment]
You are welcome! Consider it closed.
