### ISSUE TITLE
Suggestion: Add support for a greater variety of item types

### ISSUE THREAD

**Issue by Luke616** [AustereTony-MCMods/Enchantments-Control#4]
Hello,

Played around with the configuration of this mod last night, and found some small issues. Some modded enchantments by default will specify an applicable item type which does not exist in vanilla by default. 

For example, the mod "Veining" adds a veining enchantment which only works on pickaxes. It specifies "PICKAXE" as the item type, which is a string that Enchantments Control does not understand and by default enchantments control will make this enchantment available to any item. Another example are the enchantments added to shields by spartan's shields, or to throwables by spartan's weaponry. Both add custom applicable item types for Shields and Throwables, and this causes these enchantments to be applied to any item when loaded with Enchantments Control. Would it be possible to add a workaround for this?

Versions:
Forge 14.23.5.2808
Enchantments Control 1.1.0

Thanks much,
- Luke

**Comment by AustereTony-MCMods** [comment]
Hi.
Thank you for request. I figured it out at last - Forge provides modders custom enchantment types creation system and i didn't know about it. Version 1.1.2b works with such enchantment types properly. I tested it with mods you mentioned. Please check it and report.
