### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by EternalOne11** [AustereTony-MCMods/Enchantments-Control#5]
https://paste.dimdev.org/ocaniyeqez.mccrash

**Comment by AustereTony-MCMods** [comment]
Hello.
As i can see this crash happened at config loading stage, when it parsed incompatible enchantment list - so i suppose you provided wrong values. Please, check it out.
I added example images to user guide with properly defined lists. Also you can show me that enchantment config block, there you defined incompatible enchantments and i will check it.
