### ISSUE TITLE
Somes options in enchantements.json need somes explications

### ISSUE THREAD

**Issue by Fireztonez** [AustereTony-MCMods/Enchantments-Control#6]
Hello,
I try to blacklist an enchantments on certains items, but the wiki doesn't talk about that. I think your mod look really good, but for sure, the documentation have need to be updated and should have more example.

But for now, what I really whant to know, is how can I blacklist a specific enchantements (Like Mending), on somes items specific item... So, I see an option `"incompat_mode": 0` and `"incompatible": []`, but no information what it does exactly and how to make the list.

So if you can help me about that it should be really nice!!

and, little thing, I saw your mod is MIT license, so this is Open Source, but, you don't have upload the source files for your mod :D... Some time it can be really usefull to be able to look the Source Code, question to see how things works, when the documentation is not complete!

Thank's
Fireztonez

**Comment by AustereTony-MCMods** [comment]
Hello.
There are additional wiki pages with detailed user guide. Information you need is here: [user guide](https://github.com/AustereTony-MCMods/Enchantments-Control/wiki/User-Guide#incompatible-enchantments-management).

About mod sources - it always available for all supported versions. You can examine it at the main section of this repo.

Hope it will help you.

**Comment by Fireztonez** [comment]
Thank you for that guide, this is really usefull!!

**Comment by Fireztonez** [comment]
I just try to blacklist mending enchants on multiples things, but I<m still able to apply the enchant with an anvil, so, possibly I do something wrong or, the blacklist just doesn't work...

If you can help me, it should be really nice. Here what I have for mending Enchant:
https://gist.github.com/Fireztonez/c1e18771b5fbd3b2fa4ca2db2409ed57

**Comment by AustereTony-MCMods** [comment]
Hi, you should define items in "item_list" array, "incompatible" is for enchantments.

**Comment by Fireztonez** [comment]
Ok, i'm just dumb...
Thank's it work now!!
